import Link from "next/link";
export const metadata = {
    title: "Posts",
    description: "Generated by create next app",
};


async function Posts() {
    const posts = await fetch("https://jsonplaceholder.typicode.com/posts").then((res) => res.json());

    return (
        <div className="space-y-2 grid grid-cols-4">
            {
                posts.map(singlePost => <div key={singlePost.id} className="border px-10 py-3 mx-3 rounded-2xl">
                    <h1>{singlePost.title}</h1>
                    <p>{singlePost.body}</p>
                    <Link href={`posts/${singlePost.id}`}>
                        <button className="btn">View details</button>
                    </Link>
                </div>)
            }
        </div>
    )
}

export default Posts;